# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d05cc518adb699423ffeb2661b377e23f1c823e2777fadb48cf6e1e614c8e3092072888be9f9b9e96ad18a730cc6642a7990d970459b5b3299ad52a7e62bcab3

test:
  secret_key_base: 1ffdc64ab0f3713adbe59f6d111377b77455d4f8fa5642856311f0cc8e0c8e1234fe599ca056d40ccc524c0fbf32fe42c9a4f3620ffe5dab05887e6d1a09f727

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
